repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-ast
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-all
          - pydantic
          - sqlalchemy
          - alembic
          - redis
          - httpx
          - python-jose
          - google-auth
          - openai
          - tweepy
          - PyGithub
          - exa_py
          - hdbscan
          - scikit-learn
          - sentence-transformers
          - strawberry-graphql
          - structlog
          - opentelemetry-api
          - opentelemetry-sdk
          - opentelemetry-instrumentation-fastapi
          - opentelemetry-instrumentation-celery
          - opentelemetry-exporter-otlp
        args: ["--ignore-missing-imports"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.7
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.2.5
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, json, css, scss, yaml, html, markdown]
        additional_dependencies:
          - prettier@3.2.5
          - prettier-plugin-tailwindcss@0.5.11 